### ISSUE TITLE
Multiline string support

### ISSUE THREAD

**Issue by yunyu** [TroyAlford/react-jsx-parser#115]
This might be a bit out there, but I'll toss in my use case anyways. Essentially, I would like to be able to pass in nicely formatted multiline strings to a prop in my bound component. I am currently doing this like:

```
<MyComponent body={
"asdadsa\n" +
"asdadasda\n"
} />
```

However, it would be nice to have support for a subset of template literals that:

1. Doesn't necessarily support tagged templates
2. Doesn't necessarily support arbitrary interpolations (limiting it to the set of expressions supported inside JSX prop values, or not supporting interpolations altogether)

The JSX would end up looking like:

```
<MyComponent body={
`asdadsa
asdadasda`
} />
```

**Comment by TroyAlford** [comment]
This should not, in theory, be particularly difficult. Resolving the internal references shouldn't be hard to support (or limit) either, for that matter.

![image](https://user-images.githubusercontent.com/12262780/77590024-070cda80-6eaa-11ea-8f28-efabf3ae5132.png)

Running this on RunKit, we can clearly see what a template string parses into:
 - a `type: ExpressionStatement` node, whose `.expression` is:
   - a `.quasis` property: a `[type: TemplateElement]` with the string portions
   - a `.expressions` property: a `[type: Identifier]` with the list of identifiers to resolve

We could pretty easily support this, with the typical caveats about inline functions and such being unsupported/limited in support.

Would you like to put together a PR? I'm not sure when I can get to this, if you wait for me to implement - but I'd be happy to review a PR if you create one. :)

**Comment by yunyu** [comment]
I'm a bit swamped right now, but I'll take a look when I have time. Thanks for looking into this!

**Comment by TroyAlford** [comment]
This is now supported as of v1.22.0 :)
