### ISSUE TITLE
Does this work with React Native?

### ISSUE THREAD

**Issue by haveamission** [TroyAlford/react-jsx-parser#116]
Will this generate React Native components as well?

**Comment by Progr1mm3r** [comment]
Yes, it works well with React Native. As long as you include the property `renderInWrapper={false}` on `JsxParser`, the output will contain no HTML. I'm using Native Base, which is a UI library for React Native. So far I've successfully rendered `<View>`, `<Text>` and `<Icon>` elements.

**Comment by asimsagirabbasi** [comment]
that means if i have a string "some description   <AssetExample />" where AssetExample is my component . it will render AssetExample as component?

**Comment by asimsagirabbasi** [comment]
that means if i have a string "some description   `<AssetExample` />" where AssetExample is my dynamic component it will render dynamic component in react native

**Comment by Progr1mm3r** [comment]
@asimsagirabbasi that's exactly how it works. You just have to import AssetExample into your code and provide it to the JsxParser component via the components property, then it should work with any JavaScript.

**Comment by asimsagirabbasi** [comment]
> 
> 
> @asimsagirabbasi that's exactly how it works. You just have to import AssetExample into your code and provide it to the JsxParser component via the components property, then it should work with any JavaScript.

thanks for your reply but iam getting following error
 `While` trying to resolve module `react-jsx-parser` from file `\project\test\testJsxParser\App.js`, the package `\project\test\testJsxParser\node_modules\react-jsx-parser\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`\project\test\testJsxParser\node_modules\react-jsx-parser\lib\react-jsx-parser.min.js`. Indeed, none of these files exist:``

**Comment by TroyAlford** [comment]
@asimsagirabbasi it sounds like something is wrong on your end, if that file doesn't exist. You can see it in the source code here in the repo, even. Perhaps something corrupted your `node_modules`? You might want to try deleting the directory, and the `yarn.lock` file (or similar, if you're using `npm` instead) and reinstall dependencies?

**Comment by radiorz** [comment]
I try this tool but in react native 66 it has problem that Text only show the first letter and the second letter. @grahamyesfit
