### ISSUE TITLE
Binary operators ">", "<" etc not working

### ISSUE THREAD

**Issue by MatthewRandle** [TroyAlford/react-jsx-parser#117]
Comparing two numbers using binary operators...

    { 10 > 0 ? "True" : "False }

...always results in "False". Furthermore, comparing a negative number causes an error and stops the parser from running completely:

    { -1 < 0 ? "True" : "False" }

But doing this is fine:

    { -1 === -1 ? "True" : "False" }

**Comment by TroyAlford** [comment]
That's because `===` were implemented, on line 104 - but `>`, `<`, `>=`, and `<=` were not :) Apparently we forgot to implement these binary expression operators when we added support for the others.

I'm putting through a PR for this shortly, which should add the support.

**Comment by TroyAlford** [comment]
This is now supported as of v1.22.0 :)
