### ISSUE TITLE
How to parse string into react-native Component?

### ISSUE THREAD

**Issue by ghost** [TroyAlford/react-jsx-parser#122]
I want to parse a string containing `jsx` into `react-native` Component

Example: 

    const str1 = "Hi I am default text <Text style={{fontWeight: 'bold'}}>I am bold text</Text>";

Now I want to render it like below:

    const App = props => {
    
      return (
         <View>
           <Text> {str1} </Text>
         </View>
      );
    }

I should note that, the above code works if I change it to:

    const str2 = <Text>Hi I am default text <Text style={{fontWeight: 'bold'}}>I am bold text</Text></Text>;

but per my condition `str1` can be only string, because I am taking it from `TextInput Component`.

**Expectation**: `str1` should be parsed like below:

Hi I am default text **I am bold text**

**What is my goal ?**

I want to create a post, within my app, think the post text is:

Hi friends How are you please ***Like*** the post.

As you can see ***Like*** is bold an italic, so I want to make something like this.

**Comment by TroyAlford** [comment]
@muhammadwafa - the examples in the README should show pretty clearly how to do this.

```
import Text from 'wherever/you/get/Text/from'
const jsx = `<Text>Text <Text style={{ fontWeight: 'bold' }}>Bold Text</Text></Text>`

<JsxParser components={{ Text }} jsx={jsx} />
```

**Comment by ghost** [comment]
Could you please let know, will this work for `react` only ? or for `react-native` also ?

**Comment by muhammadwafa** [comment]
Does not work for react-native

**Comment by TroyAlford** [comment]
I've never used React Native for anything - but I know other people who use this lib do, and have used it successfully. Please search the other issues. Here are a few where folks discuss exactly this:

- https://github.com/TroyAlford/react-jsx-parser/issues/116
- https://github.com/TroyAlford/react-jsx-parser/issues/119
- https://github.com/TroyAlford/react-jsx-parser/issues/86

**Comment by muhammadwafa** [comment]
Thank you bro, I tested unfortunately does not support `react-native`

Cheers
