### ISSUE TITLE
TypeScript Type Declarations Missing

### ISSUE THREAD

**Issue by vinaysharma14** [TroyAlford/react-jsx-parser#123]
<img width="855" alt="Screenshot 2020-05-10 at 12 26 51 AM" src="https://user-images.githubusercontent.com/48080660/81482478-f4314800-9254-11ea-9253-309506d1dfd0.png">

**Comment by TroyAlford** [comment]
Yes, this module does not provide any TypeScript definitions, currently. It's on my list of TODO's, but I'll mark this issue for that purpose as well.

**Comment by TroyAlford** [comment]
This is now fixed & released as [v1.25.0](https://github.com/TroyAlford/react-jsx-parser/releases/tag/v1.25.0)
