### ISSUE TITLE
RenderError when components are wrong

### ISSUE THREAD

**Issue by anthowm** [TroyAlford/react-jsx-parser#131]
Hi we can use renderError as a fallback when this error triggered ?
```
The componenet <TextA> is unrecognized, and will not be rendered.
```

```
JsxParser.defaultProps = {
      components: {
        Text,
         Button
      },
      renderError: (error) => {
        return (
          <View>
            <Text>Text</Text>
          </View>
        );
        // return <ResolutionFallback />;
      },
      componentsOnly: true,
      renderInWrapper: false, // false - omit wrapping HTML element.
      showWarnings: true,
      onError: (error) => {
        console.log('ResolutionPrompt -> constructor -> error', error);
      }
    };
```

Add this snippet should do the trick ? (Will test on monday).

```
if (componentsOnly) {
        onError(new Error(`The componenet <${name}> is unrecognized, and will not be rendered.`))
if (this.props.renderError) {
        return this.props.renderError({ error: String(error) })
      }
        return undefined
}
```

**Comment by anthowm** [comment]
Hi again I clone the project and add this piece of code and for some reason is not working. Any clue what am i doing wrong? thanks
```
if (componentsOnly) {
        onError(new Error(`The componenet <${name}> is unrecognized, and will not be rendered.`))
if (this.props.renderError) {
        return this.props.renderError({ error: String('error') })
      }
        return undefined
}
```

**Comment by TroyAlford** [comment]
I don't know what's wrong with your fork - your approach seems like it would work.

It seems like your goal is simply to have the lib give you a hook so that you can render your own placeholder for any element which is unrecognized. If I'm reading that right, it seems like a reasonable feature. I'm going to put something together right now, and push a new version, to support this.

**Comment by anthowm** [comment]
@TroyAlford awesome, thanks for all !

**Comment by TroyAlford** [comment]
This is now fixed & released as [v1.25.0](https://github.com/TroyAlford/react-jsx-parser/releases/tag/v1.25.0)

**Comment by anthowm** [comment]
@TroyAlford so renderUnrecognized works like renderError right ? 
Thanks for the work !

**Comment by TroyAlford** [comment]
yes - it works similarly to what you depicted above, in your examples. It passes you the `tagName` which failed to load, and you decide how to render that.

It does _not_ pass props and such back - just the `tagName`.
