### ISSUE TITLE
packaging error while using react-jsx-parser

### ISSUE THREAD

**Issue by ronak3110** [TroyAlford/react-jsx-parser#137]
Hi,

We are using webpack and uglifyjs-webpack-plugin to bundle our package.
when we add react-jsx-praser as a dependency, while building we get an error.

ERROR in [*************]-8e2254c449ac765da505.bundle.js from UglifyJs
Unexpected token: keyword «const» [*************-8e2254c449ac765da505.bundle.js:78545,97249]

when we remove it as a dependency its working.
Apart from that when we use terser-webpack-plugin instead of uglifyjs-webpack-plugin its able to bundle it.
but at the moment we cannt move to terser-webpack-plugin because of out existing packaging structure and release process.

**Comment by leeppolis** [comment]
I'm having  similar error using it in a "standard" (meaning created with react-create-app and with all the default settings) app. The on-the-fly compiler works, but I am unable to build:

`static/js/main.ffa01338.js from UglifyJs
SyntaxError: Unexpected token: name (e) [./~/react-jsx-parser/lib/cjs/react-jsx-parser.min.js:1,99249]`

This happens both with non and yarn.

**Comment by TroyAlford** [comment]
@ronak3110 @leeppolis - can one of you please provide a minimal repro? I tested this in CRA when I made the update to 1.25.0 and it was working fine with OOTB settings, afaik - so if there's something new, I'm not sure how to repro it without an example.
