### ISSUE TITLE
rendering at inappropriate times

### ISSUE THREAD

**Issue by webciter** [TroyAlford/react-jsx-parser#138]
i have a working installation of this package using as defined, but the problem is that the render is triggered repeatedly, how can i reduce this because my component contains ajax requests, which are triggered over and over again. Which is very inefficient both bandwidth usage and cpu usage

**Comment by TroyAlford** [comment]
@webciter - can you provide a minimal repro of this? it's impossible for me to judge what's happening without seeing code.

**Comment by webciter** [comment]
fixed it, i just moved the jsxparser component out of the render function, to stop repeated mount and unmounts
