### ISSUE TITLE
Google Chrome translate breaks React JSX Parser

### ISSUE THREAD

**Issue by jazeee** [TroyAlford/react-jsx-parser#140]
In Chrome, if I right click and translate to another language, the render breaks.
Using: "react-jsx-parser": "^1.25.1"

Steps to reproduce:

1. Open the [codesandbox](https://codesandbox.io/s/react-jsx-parser-translate-bug-uxccl?file=/src/App.js) and open the rendered page in a new window (or open https://uxccl.csb.app/)
1. Right click on the full page view
1. Click Translate...
1. Click another language. (Chrome adds <font> wrappers in the code)
1. Wait up to 2 seconds for the state to update

Observe that the UI crashes
Expect it to render in a different language.

Example code:
https://codesandbox.io/s/react-jsx-parser-translate-bug-uxccl?file=/src/App.js

I have seen this issue in regular React code, and it seems to be related to this issue and solution:
https://guoyunhe.me/en/2019/06/02/fix-react-issues-with-google-translate/

The errors:
```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

```
index.js:27 The above error occurred in one of your React components:
    in div (created by JsxParser)
    in JsxParser (at App.js:18)
    in div (at App.js:11)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

Code sample:
```
import React from "react";
import JsxParser from "react-jsx-parser";

function App() {
  const [val, setVal] = React.useState(0);
  React.useEffect(() => {
    setTimeout(() => setVal(val + 1), 2000);
  }, [val, setVal]);

  return (
    <div className="App">
      <p>Open the sandbox in a new window</p>
      <p>Right click in page, and translate to Spanish</p>
      <p>Observe UI blows up</p>
      <JsxParser jsx="test" />
    </div>
  );
}

export default App;

```

**Comment by jazeee** [comment]
Note - this doesn't seem to affect jsx like `<div>test</div>`

**Comment by jazeee** [comment]
`<JsxParser jsx="test" disableFragments />` also seems to work.

**Comment by TroyAlford** [comment]
@jazeee - thanks for commenting on this, and also for posting a solution. My guess is that since Google Translate is injecting tags into the inner-rendered code, it throws off the VDom's diffing algorithm against the actual DOM - and the fragments are probably exacerbating that problem.

At the moment, I don't see a clean way to alter this behavior - so I suggest using the workaround you mention.

Happy to talk it through some more, though, if you think this is a bigger blocker, or are interested in submitting a PR to help address?
