### ISSUE TITLE
Code blocks are making trouble

### ISSUE THREAD

**Issue by bitPogo** [TroyAlford/react-jsx-parser#149]
### Background
I currently try to render some html and I run into a problem. When I have some code blocks like:
```html
<code class="language-java" data-lang="java">@Override
      protected void myAwesomeMethod() {
          super.myAwesomeMethod()
          if( this.somthing()) {
              if(this.anything()({
                 if(this.whatelse()) {
                   ...
              }
             }
         }
      } 
</code>
```
### Problem
The parser will not render due to the error message:  SyntaxError: 'super' keyword outside a method.
I assume the origin of problem is located in acron-jsx.
### Solution
Braces (`{`, `}`) must be escaped  (preferably by the user, I guess). For some reason (I have no clue) a certain number of braces  is causing that. However since this took me a amount of time to figure this out, I think it should at least be noted in the docs to help saving other peoples time.

**Comment by TroyAlford** [comment]
@bitPogo - the problem, here, is actually that the block you've submitted is not valid JSX. It's totally valid HTML, of course - but for this to be valid JSX, it would need to be:
```
<code class="language-java" data-lang="java">{`@Override
      protected void myAwesomeMethod() {
          super.myAwesomeMethod()
          if( this.somthing()) {
              if(this.anything()({
                 if(this.whatelse()) {
                   ...
              }
             }
         }
      } 
`}</code>
```

Note the extra squiggle-brackets and backticks, telling the JSX parser that its contents are a string.
