### ISSUE TITLE
Getting Error in Gatsby

### ISSUE THREAD

**Issue by bahamagician** [TroyAlford/react-jsx-parser#150]
Hi there, I'm getting an error which says "Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object."

Any idea what I might do to fix that?  Here's the code for the component: 

```javascript
import React from 'react'
import Whaps from './Whaps'
import JsxParser from "react-jsx-parser";

export default function RenderMarkup() {
    const testStr = `
    <div>
      <h3>Title from string</h3>
      <Whaps />
    </div>`;
  return (
    <div>
      <JsxParser components={{ Whaps }} jsx={testStr} />
    </div>
  )
}
```

**Comment by TroyAlford** [comment]
@bahamagician - my guess is that in `Whaps.js` you are using a named export, but here, you're treating it as a default export. As a result, when the `JsxParser` tries to instantiate an instance of that component, it's getting an object instead of a function.

**Comment by bahamagician** [comment]
Hey thanks for the really quick response :)

I don't think that's it.  Here's the code in my Whaps file:

```javascript
import React from 'react'

export default function Whaps() {
  return (
    <div>
      This is some content
    </div>
  )
}
```

Could it be that for some reason this doesn't work in Gatsby?

**Comment by TroyAlford** [comment]
I suppose that's possible - I don't know anything about Gatsby, unfortunately. What you've got here looks like it should work fine.

You might try loading in a debugger, and see if you can see what the value of `Whaps` is when it attempts to actually do the rendering?
