### ISSUE TITLE
Getting error with JSX parser

### ISSUE THREAD

**Issue by liliangiraudo5** [TroyAlford/react-jsx-parser#154]
Hello, I have the following problem : Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

I have already used this code and since my last npm update, it doesn't work anymore.

```
const Comp = (props) => {
                if (RoutePathArray.find((url) => url.id === props.idItemLink).url) {
                    return (
                        <Link
                            to={RoutePathArray.find((url) => url.id === props.idItemLink).url}
                        >
                            {props.nameItemLink}
                        </Link>
                    );
                } else return "";
            };
```

```
let text = "<p><a href="nativebrowser://www.toto.fr/">test lien</a></p>

<p>&nbsp;</p>

<p><Comp idItemLink='23512' nameItemLink='test lien 2'/></p>

<p>&nbsp;</p>

<p><a href="https://www.toto.fr/">test 3</a></p>

<p>&nbsp;</p>

<p><Comp idItemLink='23492' nameItemLink='toto'/></p>"
```

`<JsxParser components={{ Comp }} jsx={text} />`

Thank you for your help

**Comment by codegdo** [comment]
Hello,

I have same problem when update the latest package.

Thanks,
GD

**Comment by Lukavyi** [comment]
I get the same error

**Comment by patrickconroy** [comment]
Yeah getting this with something as simple as
```
import React from 'react';
import JsxParser from 'react-jsx-parser';

export default const Test = () => {
    return <JsxParser jsx={`test`} />;
};
```

More info:
~1.25 works
~1.26 does not work

I tried React 16 and 17, same issue.

**Comment by Jorenm** [comment]
Same error. Can confirm 1.25.0 works but 1.26 does not.

**Comment by TroyAlford** [comment]
Hmm. On it.

**Comment by TroyAlford** [comment]
I believe this should now be resolved. Please try `v1.26.3`, and let me know if you see further issues!

**Comment by Jorenm** [comment]
Working for me.

**Comment by wulucxy** [comment]
I have this error again, 1.29.0
