### ISSUE TITLE
<> </> Fragments shorthand don't work

### ISSUE THREAD

**Issue by Jorenm** [TroyAlford/react-jsx-parser#155]
Version 1.25.0 because later versions aren't working at all for me (as per the other open issue).

Not sure if this is a bug report or a feature request.

**Comment by TroyAlford** [comment]
hi @Jorenm :) thanks for reporting. Can you please give me a short example of what you're trying to do? Are you just trying to use something like `jsx="<>Foo</>"`? Or am I misunderstanding?

**Comment by Jorenm** [comment]
Sure. Here's an example:

```
<Lead title="Why ThoughtSpot?" html={
        <Fragment>
                <p>Sed in porta nunc. Sed ante purus, vulputate vitae dictum eu, lobortis ac turpis. Curabitur sit.</p>
                <Button link="#" color="black">Watch Film</Button>
        </Fragment>
}  />
```

Passing that as a string to JsxParser. Just, with `<>` instead of `<Fragment>` (I changed it so it'd work).

Here's the call.

```	
const parsedJSX = <JsxParser
	bindings={{}} // For event handlers
	components={ContentComponents}
	jsx={page.body}
	disableFragments={false}
	renderError={(e) => {
		console.log('renderError', e)
	}}
/>
```

**Comment by TroyAlford** [comment]
I will release support for this in the next version, coming out Soon™

**Comment by Jorenm** [comment]
Cool thanks.
