### ISSUE TITLE
Could not find a declaration file for module 'react-jsx-parser'

### ISSUE THREAD

**Issue by codegdo** [TroyAlford/react-jsx-parser#157]
Hi,

It got complaint with Typescript when I get latest version. Compile working but Typescript complaint the declaration of the library.

`Could not find a declaration file for module 'react-jsx-parser'. '/node_modules/react-jsx-parser/dist/umd/react-jsx-parser.min.js' implicitly has an 'any' type.
  Try `npm install @types/react-jsx-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-jsx-parser';`ts(7016)
`

Please help,

Thanks you.

**Comment by TroyAlford** [comment]
Patch is building. This will be released Soon™

**Comment by TroyAlford** [comment]
This is now published as [v1.27.0](https://github.com/TroyAlford/react-jsx-parser/releases/tag/1.27.0)
