### ISSUE TITLE
How to use renderError option?

### ISSUE THREAD

**Issue by Jorenm** [TroyAlford/react-jsx-parser#158]
I'm not sure how to use this. The description states  "if specified, this function can be used to render errors as a fallback", but since it's a callback I can't use it without an async context (which my react render() method is not).

Is there any way to detect an error and render some fallback JSX inside a react render() method?

**Comment by TroyAlford** [comment]
You set it as a prop, such as:
```
<JsxParser
  renderError={error => {
    // do something with the error
  })
/>
```
