### ISSUE TITLE
Add support for React 17

### ISSUE THREAD

**Issue by mihkeleidast** [TroyAlford/react-jsx-parser#159]
React 17 [was released](https://reactjs.org/blog/2020/10/20/react-v17.html) a few weeks ago.

This package's current peerDependency range does not allow React 17, which is a blocker for anyone who wants to update (and respects allowed peerDependency ranges).

**Comment by TroyAlford** [comment]
Sure - I'll expand the supported version range.

**Comment by TroyAlford** [comment]
This is now published as [v1.27.0](https://github.com/TroyAlford/react-jsx-parser/releases/tag/1.27.0)
