### ISSUE TITLE
Element type is invalid error with transpiled es5 React-JSX-Parser

### ISSUE THREAD

**Issue by kate-hall** [TroyAlford/react-jsx-parser#168]
I'm using the "older browser support" script for IE11 purposes, which worked well in 1.25.1 but not in any later versions (I've tested each, and I did update the path per the directions here, since I know it changed in ^1.26.x: https://github.com/TroyAlford/react-jsx-parser#older-browser-support).

The errors I get are similar to those in [this thread](https://github.com/TroyAlford/react-jsx-parser/issues/154), except I'm able to use the regular import but not the transpiled version. Any chance it was an oversight during fix #156 ?

![Screen Shot 2020-12-16 at 7 23 31 AM](https://user-images.githubusercontent.com/8494775/102371858-7e702600-3f73-11eb-8906-a5126541e085.png)

**Comment by kate-hall** [comment]
(For now, I'm locking to 1.25.1 and importing from the `/lib` folder that existed there!)

**Comment by TroyAlford** [comment]
@kate-hall - possibly. I also made the default import the `umd` version recently instead of the `cjs` version which used to be the default. You might try importing as `import JsxParser from 'react-jsx-parser/dist/cjs/react-jsx-parser.min.js'` and seeing if that resolves?

**Comment by kate-hall** [comment]
@TroyAlford Thanks for the fast response! Unfortunately, no, same error message with the `cjs` version too.

**Comment by TroyAlford** [comment]
@kate-hall it sounds like I may have wound up breaking the IE11 version in my later build targets. Is this still a critical issue for you? If so - I could use a small example repo that demonstrates the problem, and I'll take a look at it.

In general, though, I'm not intending to do much to support IE11 going forward, as even MS has now abandoned it.

**Comment by kate-hall** [comment]
@TroyAlford it's not critical, we can stay locked to 1.25.1 until we're officially allowed to stop supporting IE11 as well (which I hope is soon...). Thanks for the response!
