### ISSUE TITLE
exception TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by RotateAt60MPH** [TroyAlford/react-jsx-parser#170]
Hello Troy.

Kudos for this project.  It definitely fills a need for me.

I came something that has me stumped.  I've been working on a React SPA site which has been working fine, at least when running locally using 'npm start'.  I got to a certain point where I now want to 'npm run build' then publish the 'build' directory to a RHEL server and have it run from there.  

But when I attempt to run it against RHEL, an immediate javascript exception is thrown:

``` 
TypeError: Super expression must either be null or a function
```

The location of the exception is in react-jsx-parser.min.js in the following code:

```
var ge = new WeakMap(),
            xe = new WeakMap(),
            ye = new WeakMap(),
            ve = new WeakMap(),
            be = new WeakMap(),
            _e = function (t) {
          !function (t, e) {
            if ("function" != typeof e && null !== e) throw new TypeError("Super expression must either be null or a function");
            t.prototype = Object.create(e && e.prototype, {
              constructor: {
                value: t,
                writable: !0,
                configurable: !0
              }
            }), e && pe(t, e);
          }(i, t);
          var e = ce(i);
```

First assumption I made (perhaps incorrectly) is that this actually has something to to do with react-jsx-parser because that's where the exception is.  When I comment out the react-jsx-parser import (and any use of the JsxParser component), the site comes up with no error.  Simply putting the import statement back in also cause the site to fail with the same exception.

```
import JsxParser from 'react-jsx-parser';
```

Here's my react packages:

```
    "react-color": "^2.19.3",
    "react-copy-to-clipboard": "^5.0.1",
    "react-dev-utils": "^7.0.1",
    "react-dnd": "^7.4.5",
    "react-dnd-html5-backend": "^7.4.4",
    "react-dom": "^16.14.0",
    "react-jsx-parser": "^1.28.1",
    "react-redux": "^6.0.0",
    "react-redux-notify": "^4.1.1",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "^4.0.1",
    "redux": "^4.0.1",
    "redux-saga": "^1.0.0",
```

I'm also wondering it this might have something to do with the dev server not having a subpath (i.e. http:/localhost:4000) versus the RHEL server having something like 'https://fqdn.server.com/site'.

I realize this isn't a lot to go on just yet, but I thought I would post it whil eI investigate further in case someone has some further insight.

**Comment by TroyAlford** [comment]
This kind of error _usually_ has something to do with your build process. I'm not super familiar with CRA, as I rarely use it, but my understanding is that it uses `webpack` under the hood for its builds. My guess is that one of two things is happening. Either:

1. The build is not able to resolve the `JsxParser` itself (seems unlikely, as you said it works in dev mode), or
2. At runtime, the build cannot resolve the components you are binding

Can you please share a snippet of your component usage? The actual `<JsxParser />` tag, as it is used inside your component? I'm curious how you're doing your `bindings` prop.

**Comment by RotateAt60MPH** [comment]
I think I figured it out based on your suggestion to look into the build process (webpack, in this case).  After finding some similar problems, I switched the minimization engine to Uglify and the problem miraculously went away.  Go figure.

**Comment by sgtpenguin** [comment]
I just had this same issue with a CRA setup.  Works in dev mode, but upon build you get the fatal exception 
`Uncaught TypeError: Super expression must either be null or a function`
This was an old project I was coming back to.  After updating `react`, `react-dom`, and `react-scripts` to `@latest` the problem resolved.

**Comment by justinpincar** [comment]
I'm encountering this issue with Nextjs v14, the latest `react-jsx-parser`, and latest v18.2 `react`, and `react-dom`. We use the standard next build with almost no customization. I tried explicitly using the umd, cjs, and es5 builds of `react-jsx-parser`, but all had the same error. It seems it only occurs with RSC; I can use it on the client without any issues.

I've tried using different optimization/minimizer settings but that didn't seem to change anything. Any thoughts would be appreciated!

I will also note that simply importing `react-jsx-parser` causes this issue, even without any use of the `JsxParser` component.

**Comment by TroyAlford** [comment]
I'm not sure what would be causing that, unfortunately. As [you can see](https://github.com/TroyAlford/react-jsx-parser/blob/develop/package.json#L55-L56), the latest version of this library built is on `react@^16`. While it's possible that `@17` or `@18` have an incompatibility, I doubt it, as [this codesandbox](https://codesandbox.io/s/react-jsx-parser-playground-forked-6tc345?file=/src/index.js) shows it working with 18.2 of `react` and `react-dom`.

It is possible that `next.js` has some kindof incompatibility via it's builder or bundling process. I stopped using `next.js` for my projects a couple years ago, and do not do any form of compatibility testing with it at this point. If you do come across a fix, I'd be very open to a PR.

**Comment by officert** [comment]
I'm also running into this issue. I'm trying to use `react-jsx-parser` with NextJS 14, in a server component. @justinpincar Were you able to find any solution?

**Comment by justinpincar** [comment]
> I'm also running into this issue. I'm trying to use `react-jsx-parser` with NextJS 14, in a server component. @justinpincar Were you able to find any solution?

Not really. Our workaround is to render and return HTML in our API (real server, not nextjs server) for use in SSR, along with also supporting client-side rendering of markdown on navigation.
