### ISSUE TITLE
can not complie in vscode typescript project

### ISSUE THREAD

**Issue by codebdy** [TroyAlford/react-jsx-parser#171]
Dear,
I get the error:
![image](https://user-images.githubusercontent.com/18096128/103981447-c8d47380-51bc-11eb-818b-6e2e623da8e8.png)
How can I fixed it?

**Comment by TroyAlford** [comment]
I'm guessing you are running an outdated version of TS. I suggest updating to the latest.

The # character indicates a private field - and they weren't supposed syntax, iirc, until the last 6 months or so. If you update to the latest major version of TypeScript, it should be resolved.

Note that latest version of VSCode will have a pretty up to date version, but your compile prices may need you to update the local installed version in node_modules if it's older.

**Comment by codebdy** [comment]
> I'm guessing you are running an outdated version of TS. I suggest updating to the latest.
> 
> The # character indicates a private field - and they weren't supposed syntax, iirc, until the last 6 months or so. If you update to the latest major version of TypeScript, it should be resolved.
> 
> Note that latest version of VSCode will have a pretty up to date version, but your compile prices may need you to update the local installed version in node_modules if it's older.

thank you very much Sir!
I re installed typestript and solved the problem.
