### ISSUE TITLE
is array.map and the ternary operator supported?

### ISSUE THREAD

**Issue by codebdy** [TroyAlford/react-jsx-parser#172]
I want to use this amazing library as a template engine, can it suport loop and condition?like:

![image](https://user-images.githubusercontent.com/18096128/103987415-6896ff00-51c7-11eb-8a6d-a633cdb3b2c6.png)

It sames that dose not work on codesandbox.If i want to support the feathuer, how should I do it?

**Comment by codebdy** [comment]
this alsow does not work:
![image](https://user-images.githubusercontent.com/18096128/104006965-2fb85380-51e2-11eb-99a1-6967774abd4f.png)

**Comment by TroyAlford** [comment]
@rxwater - this library does not support execution of arbitrary code inside the JSX, no. Creating simple functions like what you have has been discussed a number of times, and there is a long-standing open issue about it, which you are welcome to contribute to: #114 Essentially, the lib does not support _creating_ functions inside the JSX, which is what you're doing.

Ternaries _are_ supported, however - so I'm not sure what's wrong with your second example. Unit tests to show coverage of ternaries are here: https://github.com/TroyAlford/react-jsx-parser/blob/develop/source/components/JsxParser.test.tsx#L52

Here's a screenshot of it working in CodeSandbox, as well: 
![image](https://user-images.githubusercontent.com/12262780/104131075-07873c80-5329-11eb-9fbb-3607e10d20b0.png)

**Comment by rxwater** [comment]
please helep me check,ternaries still not work:
[](https://codesandbox.io/s/jsxparser-tests-forked-oww82?file=/src/index.js)

**Comment by rxwater** [comment]
> @rxwater - this library does not support execution of arbitrary code inside the JSX, no. Creating simple functions like what you have has been discussed a number of times, and there is a long-standing open issue about it, which you are welcome to contribute to: #114 Essentially, the lib does not support _creating_ functions inside the JSX, which is what you're doing.
> 
> Ternaries _are_ supported, however - so I'm not sure what's wrong with your second example. Unit tests to show coverage of ternaries are here: https://github.com/TroyAlford/react-jsx-parser/blob/develop/source/components/JsxParser.test.tsx#L52
> 
> Here's a screenshot of it working in CodeSandbox, as well:
> ![image](https://user-images.githubusercontent.com/12262780/104131075-07873c80-5329-11eb-9fbb-3607e10d20b0.png)

please help me check,ternaries still not work:
https://codesandbox.io/s/jsxparser-tests-forked-oww82?file=/src/index.js

**Comment by codebdy** [comment]
> @rxwater - this library does not support execution of arbitrary code inside the JSX, no. Creating simple functions like what you have has been discussed a number of times, and there is a long-standing open issue about it, which you are welcome to contribute to: #114 Essentially, the lib does not support _creating_ functions inside the JSX, which is what you're doing.
> 
> Ternaries _are_ supported, however - so I'm not sure what's wrong with your second example. Unit tests to show coverage of ternaries are here: https://github.com/TroyAlford/react-jsx-parser/blob/develop/source/components/JsxParser.test.tsx#L52
> 
> Here's a screenshot of it working in CodeSandbox, as well:
> ![image](https://user-images.githubusercontent.com/12262780/104131075-07873c80-5329-11eb-9fbb-3607e10d20b0.png)

thank you very much, I think I take an old version,so get the error.
