### ISSUE TITLE
className causes silent render failure

### ISSUE THREAD

**Issue by dannoh** [TroyAlford/react-jsx-parser#173]
Unfortunately I cannot provide my code and I have not been able to repro in a smaller sample, so I'm hoping someone might be able to give some guidance as to a possible issue, how to repro it, or how to debug further.

I have a component Parent, and it renders ChildA or ChildB.  When it renders ChildA it silently fails and renders just a `<div></div>` with no errors in the console.  The root element of ChildA is `<div className="company-feature-links">`, if I change the classname to company-feature-linksA (and change the css) it works perfectly...

Version: 1.26.3 (didn't seem to be anything to address an issue like this since that version [corporate nonsense makes rev'ing annoying])

**Comment by TroyAlford** [comment]
I feel your pain :) 

I suggest turning on the following:
```ts
<JsxParser
  // other props
  onError={console.error}
  showWarnings
/>
```

That should get you some info, flowing to the console, to tell you what might be going on?

**Comment by dannoh** [comment]
Doesn't dump anything into the console

**Comment by TroyAlford** [comment]
:/ pretty hard to debug without an example.

**Comment by dannoh** [comment]
I'm trying to step through and figure out what is happening. Question though. If I have something like 
```js
const str = "<ParentComponent />";
```
Inside ParentComponent it renders `<ChildComponent />`

Does JSX do any parsing of the contents of ParentComponent or ChildComponent?  If I'm reading this right, it simply calls createElement for 'ParentComponent'.

**Comment by TroyAlford** [comment]
Yes - that's all it's going to do. You have to set up `ParentComponent` in the component bindings, but the lib doesn't do anything with the internals of it. So as long as you've got something similar to this, it should work:
```ts
<JsxParser
  components={{ ParentComponent }}
  jsx='<ParentComponent />'
/>
```

**Comment by TroyAlford** [comment]
I'm going to close this due to inactivity. Let me know if you have further questions!

**Comment by dannoh** [comment]
Thanks.  I can't even repro it anymore, so no idea what the problem was.
