### ISSUE TITLE
Can not compile when use React.forwardRef

### ISSUE THREAD

**Issue by codebdy** [TroyAlford/react-jsx-parser#174]
I have to use any type in TS:
![image](https://user-images.githubusercontent.com/18096128/104656391-2b1bff80-56fa-11eb-9832-5e30f40e6517.png)

**Comment by TroyAlford** [comment]
mmm - that sounds like a limitation of the TS typing. https://github.com/TroyAlford/react-jsx-parser/blob/develop/source/components/JsxParser.tsx#L20 declares `components` as:
```ts
components?: Record<string, Component | FunctionComponent>,
```

Looks like `React.forwardRef()` returns a `React.ForwardRefExoticComponent<React.RefAttributes<unknown>>`...

My guess is that I need to upgrade this to something like:
```ts
components?: Record<string, ComponentType | ExoticComponent>,
```
This should handle a wide variety of add'l exotics, like Memo exotics, Lazy exotics, etc.

Thanks for the report! I'll get this in as soon as I have time.

![image](https://user-images.githubusercontent.com/12262780/104659887-5828cd80-567a-11eb-8b72-4a644f09f51f.png)
