### ISSUE TITLE
Invariant Violation when using with React Native

### ISSUE THREAD

**Issue by Bootlooparn** [TroyAlford/react-jsx-parser#175]
So I'm trying to use react-jsx-parser in the following way:

```
import React, { Component } from 'react'
import { View, Text, StyleSheet, Platform } from 'react-native'
import JsxParser from 'react-jsx-parser'

interface IProps {
    body: string
}

const string = '<Text></Text>'

const WordCard: React.FC<IProps> = ({ body }: IProps) => {
    return (
        <View>
            <JsxParser jsx={'<Text></Text>'}/>
        </View>
    )
}
```
Which gives me the **error:** 
Invariant Violation: View config getter callback for component `text` must be a function (received `undefined`). Make sure to start component names with a capital letter.

When I change the string to `<Text>Test</Text>`I get this **error**:
Error: Text strings must be rendered within a <Text> component.

It's a rather simple case but I guess I'm missing something fundamental?

**Comment by TroyAlford** [comment]
The thing that jumps out at me initially is that you didn't tell the parser what `Text` is. You need a `components` pro which passes it in.

I'm not able to test at the moment to be sure, but I'm guessing the parser didn't recognize the component, so it omitted it, and since that's the entire jsx document, it has nothing left after, so it throws an error.

**Comment by Trevash** [comment]
Hey I'm doing the same thing you are in React Native @Bootlooparn, and Troy's comment is accurate. I was able to get it working by supplying the component Text in the components option. Make sure to also set the renderInWrapper prop to false or else it will wrap it in `<div>` tags that aren't understood by react native.

`
<JsxParser renderInWrapper={false} components={{ Text }} jsx={'<Text>Test</Text>'} />
`

Let me know if that makes sense

**Comment by TroyAlford** [comment]
I'm going to close this issue, for now. Please feel free to reopen or ask more questions, if needed.
