### ISSUE TITLE
setState parent data  lead to children Input compoenent focus out 

### ISSUE THREAD

**Issue by lsai2270** [TroyAlford/react-jsx-parser#179]
![image](https://user-images.githubusercontent.com/32258110/107192810-139a1300-6a29-11eb-8774-f44bff1e72e6.png)
![image](https://user-images.githubusercontent.com/32258110/107192940-39271c80-6a29-11eb-9a01-ce70d0138860.png)
i see you code find your use random to set key lead to render and create new components .lead to input once and focus out ,so i try to use components length to set key ,it's kan solve problems

**Comment by TroyAlford** [comment]
Did you try just setting `disableKeyGeneration`? That turns off the random generated keys

**Comment by TroyAlford** [comment]
Closed due to inactivity.
