### ISSUE TITLE
postinstall script with private registry failed

### ISSUE THREAD

**Issue by giuvincenzi** [TroyAlford/react-jsx-parser#182]
When using private registry with authorization required, the 401 error is thrown when the postinstall script (`npx patch-package`) is run.

The problem could be related to not copying the project's `.npmrc` file.

**~/project1/.npmrc**

```yaml
registry=http://myIp:myPort/

//myIp:myPort/:_authToken="myAuthToken"
```
**~/.npmrc**
```yaml
registry=https://registry.npmjs.org/
```
When the `patch-package` script is run with `npx`, the project's `.npmrc` file is not used but the user's `.npmrc` file is used.
If I copy the configurations of `~/project1/.npmrc` to the `~/.npmrc` file the `npx patch-package` script works fine.

In this issue https://github.com/ds300/patch-package/issues/148 the problem of copying the local npmrc file to the project has been fixed.
It is possible that when running the script with `npx` somehow local configurations are ignored and user npm configurations are used?

Momentarily I pinned version 1.28.1 which does not have the postinstall script and everything continues to work

**Comment by TroyAlford** [comment]
Hmm... I'm afraid this kind of situation is something I can't easily replicate. Do you have a good way to produce a minimum repro that I could pull & work with?

**Comment by soroushm** [comment]
> Hmm... I'm afraid this kind of situation is something I can't easily replicate. Do you have a good way to produce a minimum repro that I could pull & work with?

@TroyAlford its when happened while users have a [private NPM](https://cloudsmith.com/npm-registry/?utm_term=private%20npm%20registry&utm_campaign=Search+%7C+Packages/Repositories+%7C+Europe&utm_source=adwords&utm_medium=ppc&hsa_acc=2785245595&hsa_cam=8111390308&hsa_grp=85502092482&hsa_ad=629159278477&hsa_src=g&hsa_tgt=kwd-353962340762&hsa_kw=private%20npm%20registry&hsa_mt=e&hsa_net=adwords&hsa_ver=3&gclid=CjwKCAjw5P2aBhAlEiwAAdY7dDAcH0-FMgBlui3patStkXrtjucnupVY7e2Pqe0VTEzMjd5YsWjJghoCwZYQAvD_BwE) at that moment the package is not exist on [npmjs.com](https://npmjs.com/) so libraries cant find it then return an error
```
node_modules/patch-package/dist/makePatch.js:219
        throw e;
        ^
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 29841,
  stdout: null,
  stderr: null,
  error: null
}

```
usually we are install the packages with registry flag `npm i --registry=https://npm.privateDoamin.com`
its good to have semilaur here
```
# run patch-package to create a .patch file
npx patch-package some-package --registry=https://npm.privateDoamin.com
```
