### ISSUE TITLE
Error when style tags are not escaped

### ISSUE THREAD

**Issue by chaddjohnson** [TroyAlford/react-jsx-parser#184]
Hello! Thanks for the great library.

I'm noticing that unless I escape `<style>` tag contents, I get an `Unexpected token` error. A string like this yields the error:

```jsx
<style>
  .popup { background-color: red; }
</style>
```

escaping like so remedies the problem:

```jsx
<style>{"  .popup { background-color: red; }  "}</style>
```

or

```jsx
<style>{"
  .popup { background-color: red; }\
"}</style>
```

Here is a possible fix:

```javascript
const escapedString = string.replace(
  /(<style[^>]*>)([\s\S]*)(<\/style>)/gim,
  function (match, group1, group2, group3) {
    return `${group1}{"${group2.replace(/\n/gm, '')}"}${group3}`;
  }
);
```

Would it make sense to integrate such a fix into this library? Would a pull request be suitable, or has such a fix intentionally been avoided?

**Comment by TroyAlford** [comment]
Yes, that would work. My only reticence is that what you're proposing is
not actually valid JSX :/ so we'd need to have some kind of opt-in, I think.

**Comment by chaddjohnson** [comment]
Probably a good call about an opt-in.

Looks like this is no longer a need on my end. I ended up using Handlebars in conjunction with React for the particular challenge I was facing. `react-jsx-parser` is excellent, but I decided against letting my end users edit JSX. Going to keep it simple and just give them variable placeholders.

**Comment by TroyAlford** [comment]
Makes great sense. :) Best of luck!
