### ISSUE TITLE
Cannot use cjs version on local development

### ISSUE THREAD

**Issue by arjanvillon** [TroyAlford/react-jsx-parser#188]
Hi,

This is an awesome tool. I've stumbled upon a bug last time on production but it was fixed with the help of the cjs version which i imported from `react-jsx-parser/dist/cjs/react-jsx-parser.min.js`. However, when I use the same import for the local development, it doesn't work properly and throws an error.

**Comment by TroyAlford** [comment]
In your scenario, are you using an off-the-shelf tool like CRA? or do you have your own rollup/webpack/parcel type bundler?

**Comment by arjanvillon** [comment]
Yes, I'm using CRA for the development of the project

**Comment by TroyAlford** [comment]
@arjanvillon I don't use CRA for anything, myself. Is this an easy behavior to reproduce? Could you throw up a small repro lib or something which shows the issue?

You haven't given me much to go on, here. What's the error, even?
