### ISSUE TITLE
Uncaught TypeError: p is undefined

### ISSUE THREAD

**Issue by webciter** [TroyAlford/react-jsx-parser#189]
getting Uncaught TypeError: p is undefined when parsing HTML

this causes it
```
<html>
    
    test
</html>
```

but not this
```
<a>
    
    test
</a>
```

**Comment by DamianoNaraku** [comment]
To include the scripts, the initial page is bound to already have at least the `<html>` tag.
This is probably related to the attempted generation of an invalid DOM tree with nested `<html>` tags.

**Comment by TroyAlford** [comment]
Yes - your document should not have an `html` tag in it. The parser parses JSX fragments, not entire HTML pages. We might want to better handle this case in the future - but I don't think this should be considered unexpected.
