### ISSUE TITLE
Typescript error suggesting components passed to component prop should have no props itself

### ISSUE THREAD

**Issue by YoofiBP** [TroyAlford/react-jsx-parser#209]
I have created a custom component as below:

```
function CustomDialog({title, content}: { title: string; content: string })  {
    return (
        <div>
            <h1>{title}</h1>
            <p>{content}</p>
        </div>
    )
}
```

When I try to use this component in the JsxParser as below:

```
<JsxParser jsx={jsx} components={{CustomDialog}}/>
```

I get the following Typescript error

`TS2769: No overload matches this call.   
Overload 1 of 2, '(props: TProps | Readonly<TProps>): JsxParser', gave the following error.    
 Type '({ title, content }: { title: string; content: string; }) => Element' is not assignable to type 'ComponentType<{}> | ExoticComponent<{}>'.       
Type '({ title, content }: { title: string; content: string; }) => Element' is not assignable to type 'FunctionComponent<{}>'.  
Types of parameters '__0' and 'props' are incompatible.           
Type '{ children?: ReactNode; }' is missing the following properties from type '{ title: string; content: string; }': title, content   Overload 2 of 2, '(props: TProps, context: any): JsxParser', gave the following error.     Type '({ title, content }: { title: string; content: string; }) => Element' is not assignable to type 'ComponentType<{}> | ExoticComponent<{}>'.       
Type '({ title, content }: { title: string; content: string; }) => Element' is not assignable to type 'FunctionComponent<{}>'.`

I noticed when I remove props from CustomDialog the error goes away. However, in the examples in the docs, I notice that components with props are used. Can anyone assist as to what to do

**Comment by TroyAlford** [comment]
I can't test this at the moment, but my suspicion is that TS is confused by the destructuring and inline definition. Also the fact that you're providing an incomplete set of types for a component (`children?: ReactNode` should be a member).

Try this:

```ts
interface Props {
  children?: ReactNode,
  content: string,
  title: string,
}

function CustomDialog({title, content}: Props)  {
    return (
        <div>
            <h1>{title}</h1>
            <p>{content}</p>
        </div>
    )
}
```

**Comment by davemssavage** [comment]
@TroyAlford are you sure this is fixed? The following code fails for me

```typescript
import { ReactNode } from "react";
import JsxParser from 'react-jsx-parser'

export default function JSXParserTest() {

    interface Props {
        children?: ReactNode,
        content: string,
        title: string,
    }

    function CustomDialog(props: Props) {
        return (
            <div>
                <h1>{props.title}</h1>
                <p>{props.content}</p>
            </div>
        )
    }

    return (
            <JsxParser
                components={{ CustomDialog }}
                jsx={'<CustomDialog title="foo" content="bar"/>'}
            />
    )
}
```

However this works:
```typescript
import { ReactNode } from "react";
import JsxParser from 'react-jsx-parser'

export default function JSXParserTest() {

    interface Props {
        children?: ReactNode,
        content: string,
        title: string,
    }

    function CustomDialog(props?: Props) {
        return (
            <div>
                <h1>{props?.title}</h1>
                <p>{props?.content}</p>
            </div>
        )
    }

    return (
            <JsxParser
                components={{ CustomDialog }}
                jsx={'<CustomDialog title="foo" content="bar"/>'}
            />
    )
}
```
This precludes using any components that have mandatory attributes I suspect the problem is somewhere around here: https://github.com/TroyAlford/react-jsx-parser/blob/develop/source/components/JsxParser.tsx#L52 as React.ComponentType is parameterised with the set of attributes a component accepts but defaults to {} if no parameters are supplied
