### ISSUE TITLE
render syntax {{ hello }}

### ISSUE THREAD

**Issue by duchuy2707** [TroyAlford/react-jsx-parser#213]
Help me
How to render text {{ hello }} don't using Identifier react

`<JsxParser jsx="{{ hello }}" />`

**Comment by TroyAlford** [comment]
The problem with your example is that it's not valid JSX.

When you use `{{}}` (double curlies), you are indicating that you're binding an object. An object is not valid as a top-level JSX element - so this just explodes.

If you want the _text_ "hello", you should simply use:
```ts
<JsxParser jsx="hello" />
```
or
```ts
<JsxParser jsx="<span>hello</span>" />
```

**Comment by duchuy2707** [comment]
what i mean is when the user enters any text and i use JSXParser to render, the text is in {{}}, how can JSXParser understand it's just text and ignore

ex
`<JsxParser jsx=" {{ I want to display text in {{}} }}" />`

all characters in jsx string are interpreted as characters and not any constraints
i know {{}} ( double-curve ) is binding an object, but i just want render is a text

**Comment by TroyAlford** [comment]
You're going to have to escape them. Ensuring that user-input is valid is something you must handle outside the parser.

As an example, you might wish to do something like:
```ts
const jsx = userInput.replace(/\{/g, '&#x7B;').replace(/\}/g, '&#x7D;')
```
This will turn `{{ foo }}` into `&#x7B;&#x7B; foo &#x7D;&#x7D;` (HTML-encoded).

The problem with this approach is that you actually _do_ want to use any `{}` in your JSX, you'll have to figure out how to _not_ encode those. This is up to your application logic, and not something this component can handle for you.

**Comment by duchuy2707** [comment]
Thank you for support !

**Comment by TroyAlford** [comment]
my pleasure :)
