### ISSUE TITLE
trim() is called when receiving a number

### ISSUE THREAD

**Issue by frandevel** [TroyAlford/react-jsx-parser#214]
`VM91451:1 Uncaught TypeError: e.props.jsx.trim is not a function`

This is what we get when debugging and checking that a `13` (number type) is arriving into the `jsx`pro
<img width="669" alt="Captura de pantalla 2021-11-16 a las 10 28 23" src="https://user-images.githubusercontent.com/684869/141959007-cb403741-bbd2-4a5f-adf5-82c19d111387.png">

**Comment by TroyAlford** [comment]
This doesn't give me nearly enough information to reproduce what you are trying to do. What is the value of `jsx` that you are passing into the prop? A numerical value?

If you attempt to do something like:
```ts
render = () => {
  const jsx = 4; // a number
  return <JsxParser jsx={jsx} />
}
```
You will, of course, have a problem when the parser attempts to process - as the value you've passed is a number, not a string - while the typesafety requires it to be a string.

**Comment by frandevel** [comment]
Thanks @TroyAlford , we modified our code to make sure we always pass a string to the jsx parsing logic.
Nevertheless, would be nice that the jsx parsing took care of ensuring that it's converted to a string. I guess it would not harm the parsing process and would be a bit more robust.
Sorry for not being able to provide more accurate information to reproduce the issue, but we debugged for a long while on production (without source maps) until we found out it was related to this problem.
What do you think?
