### ISSUE TITLE
v1.23.0 introduced a breaking change in which <div children={} /> no longer works

### ISSUE THREAD

**Issue by AgileEduLabs** [TroyAlford/react-jsx-parser#231]
Hi Troy, thanks for putting together this wonderful package. I just want to share the following in case somebody else is having the same issue:

Assume that we have
`let bindings={ aChild: <span>hello!</span> }`
`let jsx = "<div children={aChild} />"`
`<JsxParser bindings={bindings} jsx={jsx} />`

v1.23.0 introduced a breaking change in which `<div children={aChild} />` no longer works. A simple workaround is to instead use `<div>{aChild}</div>`

**Comment by TroyAlford** [comment]
Applying `children={obj}` is generally an anti-pattern in JSX, to begin with. The way you've rewritten this is the more appropriate JSX methodology. I would also point out that you can probably do `<>{aChild}</>` without introducing an extra (and potentially layout-breaking) `div`
