### ISSUE TITLE
props.children?

### ISSUE THREAD

**Issue by jimothyhalpert7** [TroyAlford/react-jsx-parser#232]
When using a React component, we can access its children through `props.children`.
The `props` object returned by JSXParser doesn't seem to have a `children` key.
How can this be done?

**Comment by TroyAlford** [comment]
I don't really understand your question. The `JsxParser` automatically parses the `jsx` prop to auto-create its own `children`, you don't provide them to it via `<JsxParser><some-children /></JsxParser>` or similar.

What is the context in which you are trying to programmatically access the component's `children`?

**Comment by jimothyhalpert7** [comment]
Thanks for the speedy reply @TroyAlford 

Our goal is to copy a component with all of its children and add the name property to some of those children.
Example: we have a `MainComponent()` that returns
```
<div>
  <div></div>
  <CustomComponent />
  <div></div>
</div>
```

We want to set a `name` to all custom components.
The way we do it right now is we loop through all three of the `MainComponent().props.children`, and check if `child.type !== "string"`.

When we pass the above DOM tree to JsxParser, there is no way for as to access the array containing the three child components.

**Comment by TroyAlford** [comment]
Can't your `CustomComponent` component simply apply a name? This seems like more of a concern of the components, rather than a concern of the JsxParser, to me.

**Comment by jimothyhalpert7** [comment]
@TroyAlford we have several `CustomComponent`s. 
I guess what we can try is to let CustomComponent generate a random name every time it's initialized.

Coming back to the original question - when I spoke of `.children` I assumed that the jsx had one parent component, that has other components nested in it (like the example above). This is not a requirement I guess, so let me paraphrase the original question -
is there a way for JsxParser to return a list of React components, based on the jsx we provided, so that we can change the e.g. `name` property of each, before we return it to render?

**Comment by TroyAlford** [comment]
To do it the way you're describing, you'd need to fork this repo to introduce a new function. :\

A couple other options for you...
 - you could pre-process the JSX as if it were XML, which is how this code used to work. You could then add a `name` property dynamically to each node whose name started with a capital letter (if you can get XML to tell you which those are)
 - you could use a binding. Something like `bindings={{ randomName: someRandomNameFunction }}`, and then in the JSX apply a custom property to each component using `name={randomName()}`
 - you could use a base class or some other method of creating commonality of this function for each of your CustomComponents (which is my strongly recommended method)

If I were doing this using class components, I would do something like:
```ts
// ComponentBase.tsx
import { generateRandomName } from './somewhere'

interface Props {
  name?: string,
}

export class ComponentBase extends React.Component<Props> {
  static defaultProps: Props = {
    name: null,
  }

  constructor(props: Props) {
    super(props)
    props.name ??= generateRandomName()
  }
}

// CustomComponentA.tsx
type Props = ComponentBase['props'] & {
  myOtherProp: string,
}

export class CustomComponentA extends ComponentBase<Props> {
  static defaultProps: Props {
    ...ComponentBase.defaultProps,
    myOtherProp: 'default value',
  }
}
```

This lets the base class handle auto-applying the prop.

If I were doing this with hooks-style components, I'd probably do something like:
```ts
import { generateRandomName } from './somewhere'
import { BaseProps } from './BaseProps'

type Props = BaseProps & {
  myOtherProp?: string,
}

export const CustomComponentA = (props: Props = {}) => {
  const { name = generateRandomname() } = props

  return <div className="custom component">{name}</div>
}
```

Note - all of the above is pseudo-code. I did not attempt any of it in an actual compiler, so there may be (even glaring) errors.

All of this said - why are you trying to generate a random name on every render? That seems like a pretty strange requirement. If you explain what you're trying to accomplish, I might have other suggestions.
