### ISSUE TITLE
Problem Loading Google Fonts

### ISSUE THREAD

**Issue by chenkie** [TroyAlford/react-jsx-parser#249]
Thanks for the great library! 

Everything is working well but I'm having some trouble loading fonts from Google.

I can wrap my user-generated JSX in an `html` tag with a `head` and `body`. In the `head`, I can load things like Tailwind.

```js
const jsxContent = `<html><head><link href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet" /></head><div>${content}</div></html>`;
```

But when I try to do the same with a font from Google Fonts via their API, I get a blank render.

To be more precise, what is rendered when I try to get a Google Font is exactly this:

```html
<div class="jsx-parser"></div>
```

Is there something that is stripping deliberately stripping out the content in this case? Any way to override it?

Many thanks!

**Comment by TroyAlford** [comment]
That generally only happens when you input something that won't parse. Can
you share the exact code you are trying to use?

**Comment by chenkie** [comment]
Sure thing!

Here's my exact code block that works (with some other surrounding code for more context):

```js
const data = payload || template.data;

const fontStyles = 'p{font-family: "Open Sans", sans-serif !important;}';

const jsxContent = `<html><head><style>{'${minifyStyles(
  template.styles
)}'}</style><style>{'${fontStyles}'}</style><link href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet" /></head><body><div>${sanitizeContent(
  template.content
)}</div></body></html>`;

const Document = () => {
  return <JsxParser bindings={data} jsx={jsxContent} />;
};

const content = ReactDOMServer.renderToStaticMarkup(<Document />);
```

Here's the code when it produces the blank. The change here is I've added a link to a Google font in the `head`.

```js
const data = payload || template.data;

const fontStyles = 'p{font-family: "Open Sans", sans-serif !important;}';

const jsxContent = `<html><head><style>{'${minifyStyles(
  template.styles
)}'}</style><style>{'${fontStyles}'}</style><link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><link href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet" /></head><body><div>${sanitizeContent(
  template.content
)}</div></body></html>`;

const Document = () => {
  return <JsxParser bindings={data} jsx={jsxContent} />;
};

const content = ReactDOMServer.renderToStaticMarkup(<Document />);
```

Apologies for the collapsed tags in `jsxContent`. Things break if I bump down to new lines for some reason.

**Comment by TroyAlford** [comment]
One of your link tags doesn't have a /> at the end. The parser likely can't
handle that, and thus thinks the entire block is invalid and thus renders
blank

**Comment by TroyAlford** [comment]
Specifically, the Google fonts tag.
