### ISSUE TITLE
Arrow function issue

### ISSUE THREAD

**Issue by LR17** [TroyAlford/react-jsx-parser#250]
Hello,
Is this use case supported by the library?

`<JsxParser
      components={{ Custom }}
      bindings={myFn: (param) => {}}
      jsx="{items.map(item => <Custom binding={myFn(item.someProp)}</Custom>)}"
 />`

Inside myFn param is always undefined

**Comment by TroyAlford** [comment]
No, as the README states, this lib does not support inline declarations of arrow functions. Your definition of myFn as a binding is fine, but the inline arrow function inside the .map call won't process correctly

**Comment by LR17** [comment]
From my understanding of the README this simple arrow function is supported:
` (item) => <p>{item.name}</p>`

Indeed the the arrow function in my example is working. What is not working is the `binding` property value when I use a reference to myFn
