### ISSUE TITLE
Question for binding

### ISSUE THREAD

**Issue by cozy819** [TroyAlford/react-jsx-parser#254]
I have question for binding function. 

Using React ver.16.14.0 and react-jsx-parser ver.1.27.0

My code is 
```
<JsxParser
    bindings={{
        propStringTest: 'propStringTest',
        propFunctionTest: () => {
            console.log('alert!!!!');
        },
    }}
    components={{ TextArea2 }}
     jsx={`
        <div>
            <TextArea2
                labelCode="useYn"
                labelName="useYn"
                modelAttr={propStringTest}
                requiredAttr={true}
                readonlyAttr={false}
                onChange={propFunctionTest}
            />
        </div>`
    }
/>    
```
    
In bindings, propStringTest works.
But the problem is propFunctionTest doesn't works.

**Comment by cozy819** [comment]
on

**Comment by mk0y** [comment]
How did you resolve this?

**Comment by TroyAlford** [comment]
The default value for `blacklistedAttrs` blocks `/^on.+/i` props from being bound. There's documentation on the [README](https://github.com/TroyAlford/react-jsx-parser/?tab=readme-ov-file#proptypes--settings) about it.

If you want to allow `on*` bindings, you need to set `blacklistedAttrs={[]}` (or a different regexp)

**Comment by cozy819** [comment]
In my case, a word of  "onChange"  make problem.
I had changed this word something different, then it works.

**Comment by mk0y** [comment]
My problem was that the component was wrapped within another library react-dnd, and *that* was making problems, i.e. not allowing me to use keyboard. Thanks!
