### ISSUE TITLE
Can't parse component composition - only functions props

### ISSUE THREAD

**Issue by YossiSaadi** [TroyAlford/react-jsx-parser#255]
Reproduce:
https://codesandbox.io/p/sandbox/react-jsx-parser-1-29-0-component-composition-b-53qnmd

```
const jsx = `<Button someComponent={Component}>I'm children</Button>`
...
<JsxParser components={{ Button, Component }} jsx={jsx} />
```

```
const Button = ({ someComponent, children }) => {
  return <button>{someComponent || children}</button>;
};
...
const Component = () => {
  return <div>I'm some component</div>;
};
```

Result:
![image](https://github.com/TroyAlford/react-jsx-parser/assets/30905362/8002ef1a-79b4-4001-9131-05f63db5527a)

**Comment by TroyAlford** [comment]
Yes, that is somewhat strange behavior - but I'm not sure why you would expect the Component to render. You neither rendered it nor invoked it.
