### ISSUE TITLE
v2.2.0 is bundling react and react-dom, causing "multiple copies of react" errors

### ISSUE THREAD

**Issue by chrisqualitee360** [TroyAlford/react-jsx-parser#292]
I know you don't use Next.js, so are dubious about supporting it.  Just thought I'd put this issue up in case others run into it.  Next.js 15 complains that what JSXParser emits for React is unsupported.  I removed JSXParser from my project and everything else works fine, so it's definitely JSXParser that's causing this issue.

Error: A React Element from an older version of React was rendered. This is not supported. It can happen if:
- Multiple copies of the "react" package is used.
- A library pre-bundled an old copy of "react" or "react/jsx-runtime".
- A compiler tries to "inline" JSX instead of using the runtime.

**Comment by TroyAlford** [comment]
@chrisqualitee360 hmmm... this actually indicates that the current bundle is _including_ `react` and `react-dom` instead of marking them `external`. That's problematic!

I just confirmed that the build script needs an update, and I'll do a little work here to get it out. Thank you!

**Comment by TroyAlford** [comment]
_hopefully_ this is fixed now. Please pull latest and let me know?

**Comment by chrisqualitee360** [comment]
Unfortunately, I had to move away from JSXParser (found another way to do what I need without it).  I no longer have a test bench for this fix.  Thank you for looking into this, though.  I'm sure others will find this fix useful.
