### ISSUE TITLE
Using components as * from

### ISSUE THREAD

**Issue by mk0y** [TroyAlford/react-jsx-parser#297]
Hi,
Is it possible to have the following scenario?

Let's say i have many components to import, but i want to put in the `components` prop just one object which holds all of them. For example:

```tsx
import * as AllComponents from "@/components/all";

<JsxParser 
    components={{ AllComponents }}
    onError={console.log}
    jsx={jsx}
/>
```

And all.tsx would look like:

```tsx
export { Button } from "@/components/Button";
export { Input } from "@/components/Input";
// ...
```

It's pretty standard procedure when it comes to design systems, i was wondering if it's possible to somehow use it in `components` prop instead of manually putting them there each time we have a new component. I realize that it's an object in this case and not a React compatible type.

Of course, i would use `AllComponents.Button` in the jsx string.

Thanks!
Marko

**Comment by mk0y** [comment]
Surprisingly easy...

```tsx
<JsxParser 
    components={{ ...AllComponents }} // destructuring helps
    onError={console.log}
    jsx={jsx}
/>
```

I just needed to use "export {...} from" syntax instead.

**Comment by ThatsEmbarrassing** [comment]
Hey!

It is technically possible. You can check it easy. Currently, the one problem is the `component` prop type which does NOT include nested records. See: https://github.com/TroyAlford/react-jsx-parser/issues/306
