### ISSUE TITLE
[feature] Make custom elements optional in the jsx input

### ISSUE THREAD

**Issue by daformat** [TroyAlford/react-jsx-parser#32]
If you do pass some components to JsxParser, then they **have to be** in the jsx input, otherwise JsxParser will trigger an error and the output will be empty.

## Use-case
I do have a single page webapp built with React and React-router. A lot of my app pages depends on dynamic html content that is stored across a bunch of json files, that are loaded depending on the route.

The html content *can* of course have `<a>` html tags, **but it's not always the case.**

Those links are the reason I started using `JsxParser`: given my json object, I can replace `<a>` tags with some custom wrapper built on-top of React-router's `<Link>` component. This way I can have dynamic content within my app and still benefit of the router's functionality so the whole page doesn't refresh whenever the user clicks on an internal link that would have been within the html content.

Whenever my html had links `JsxParser` would happily process it and create the React components, but the situation is different when there is no link in the input, JsxParser would then trigger an error.

## Workaround and feature-request
The workaround for me was to conditionally use either `JsxParser` or React `dangerouslySetInnetHtml` prop based on wether or my html content had some links. It's not really complicated to do, but I was thinking this use-case should be pretty common, and if there's an easy way to make those custom components optional in JsxParser, it would make it even easier to use.

This way you could use out of the box something like:
```jsx
<JsxParser
  components={{
    Link
  }}
  jsx={loadedHtml}
  />
```

Without even having to think about wether or not your `loadedHtml` has links or not. It wasn't really clear tom me after reading the README, so maybe it's worth mentioning about this.

**Comment by TroyAlford** [comment]
Hey @daformat - thanks for the issue report. I'm not actually sure I understand your use-case.

From what you're describing, your HTML contains `<a ... />` elements, not `<Link ... />` elements - so the `Link` component wouldn't do anything at all, anyway. The only way the `Link` component would parse `<a ... />` tags is if you specified it as: `components={{ a: Link }}`

Can you give me an example or repro code to look at?

**Comment by daformat** [comment]
Thanks Troy for the quick reply, and sorry I wasn't thorough enough in the report and testing, I must have had another bug that was causing the parser to fail, because as I was getting some example code ready for you, the parser wasn't failing any longer.

I'm going to close this issue, as it was definitely on my end, however, I'm confused about using `components={{ a: Link }` : would this turn `href` props to `to` props?

**Comment by TroyAlford** [comment]
The `components` prop expects a map of tag-names to components. When you do `components={{ Link }}` what you're actually saying is - `components={{ Link: Link }}` - the shorthand just allows you to remove the repetition. The first `Link` is the `key` in the named value pair, and the second is the `Link` element which you are mapping to it.

The lines where this matter are: https://github.com/TroyAlford/react-jsx-parser/blob/develop/source/components/JsxParser.js#L90-L103

Essentially, whenever the component parses a tag, it first checks to see whether it has a mapping for a tag of that name (in this case it would be a `<Link ... />` tag, which we've mapped). If so - it does some other processing, but uses the passed-in component to render.

If it doesn't find a match, it will simply render it as-is, via https://github.com/TroyAlford/react-jsx-parser/blob/develop/source/components/JsxParser.js#L120
