### ISSUE TITLE
No render with `<div class="jsx-parser">`

### ISSUE THREAD

**Issue by stoplion** [TroyAlford/react-jsx-parser#34]
Is there a way to have jsx not render in an `<div class="jsx-parser">`?

**Comment by TroyAlford** [comment]
Hmm... I suppose now that React 16 allows returning multiple components, it would be possible to suppress the container itself. Can you tell me a little more about your use-case and what problem the containing `<div>` causes?

**Comment by stoplion** [comment]
I'm passing in some components from that result in some [mjml](https://github.com/mjmlio/mjml) (to build email templates). The Mjml parser is kind of particular, and expects a certain nesting order of markdown (mjml). I could use something like Cheerio to take the `<div class="jsx-parser">`, but I wasn't sure if there was an option that could be passed to that happen already...

**Comment by TroyAlford** [comment]
Oh neat - that's a cool use-case. :)

No - there's no pre-existing option, but I think it's a totally reasonable thing to do. We could actually allow the output by just using the new [Fragment Syntax](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html) that React 16.2.0 introduced.

I'm thinking perhaps it can be enabled via a new prop, named something like: `suppressWrapperTag`.

**Comment by TroyAlford** [comment]
Closed by #35, and released in v1.2.0 :)

**Comment by george-norris-salesforce** [comment]
Aweome! 😎
