### ISSUE TITLE
Custom elements must have closing tags

### ISSUE THREAD

**Issue by TroyAlford** [TroyAlford/react-jsx-parser#4]
After switching from `application/xml` based parsing to `text/html` parsing, one of the side-effects is that the typical `<Component />` syntax no longer works consistently.

When rendering something like:
```javascript
<Component />
<div>Text</div>
```
... the `DOMParser` will automatically rewrite to 
```javascript
<Component>
  <div>Text</div>
</Component>
```
...because custom void elements are not allowed by HTML5.

This is pretty annoying, tbh, from a usability standpoint - but the easiest alternative is to parse as `application/xml` - which causes several other issues. The biggest of these is that valid void elements, such as `<img>` wind up being treated as invalid XML - and all sorts of strange "corrections" are made to the rendered DOM as a result, prior to actual processing/parsing.

For now, the tradeoff I'm sticking with is to stick with `text/html` parsing - because then at least the corrections to DOM are more intuitive, as they match the corrections the browser is already making. (Adding `<tbody>` around `<tr>` and such.)

In the future - maybe it would make sense to do some additional pre-parsing and attempt to apply corrections to the raw HTML/XML string prior to `DOMParser` getting ahold of it - or using some other type of parser... but for the moment, I don't want to expand the footprint and complexity of the component simply to avoid closing tags.

**Comment by aturner-andplus** [comment]
Any update on this or anything I can do to help?

**Comment by TroyAlford** [comment]
I'd certainly love some help with it. I've considered experimenting with a library like `Cheerio`, to see if it's parsing algorithm can handle this better - but I'm very resistant to increasing the size of the package by including a large dependency.

Looking at how Babel parses JSX might be good, too - perhaps there is a clever way.

A third option might be to do a bit of pre-parsing as plain text, resolving specifically these void tags, then passing the resulting string along to the existing methodology.

If you wanted to create a PR, I'd be happy to contribute and with on it together.

**Comment by aturner-andplus** [comment]
Hrm, `Cheerio` being the server side jQuery clone? I'm not super sure that would help here

**Comment by TroyAlford** [comment]
Yes - mostly I'm just wondering if it has its own parser (I haven't looked). If you have any other ideas for how to address, I'm very open to that, too.

**Comment by aturner-andplus** [comment]
Out of curiosity, why was `application/xml` ditched? That would seem more appropriate than text/html

**Comment by TroyAlford** [comment]
The problem with `application/xml` is that it rejects valid tags like `<img />`, because they have no closing tag. When `DOMParser` encounters those, it treats them as invalid XML - and simply returns an error.

For HTML tags, one solution might be to pre-parse [void nodes](https://github.com/TroyAlford/react-jsx-parser/blob/develop/src/constants/specialTags.js#L1-L18) and convert them to having closing tags (invalid HTML, but now valid XML) - then use the `application/xml` parser. This doesn't solve the issue for actual JSX nodes, though, cleanly.

If you encountered `<MyComponent />` - you'd have to fall to some kind of regex parsing or something (notoriously problematic / hard) in order to add the closing tags.

Since this is the primary use-case the component is supposed to support, it seems cleaner to use `text/html` to parse. Open to suggestions, as I said.

**Comment by jonjaques** [comment]
It adds some bloat (~68kb), but I've had success with `acorn-jsx`: https://gist.github.com/jonjaques/25ca10488bde40d53fdc9fbf305b579a

```
let tpl = '<Test test={foo}>{things}<Single /></Test>'
<JSXParser bindings={{foo: 'bar', things: 'stuff'}} template={tpl} components={[Test, Single]} />
```

Right now it only support direct bindings, but my plan is to add in property access and some rudimentary handling for events. Not sure what the api should look like for that though as I don't want to parse/eval functions.

**Comment by TroyAlford** [comment]
Oh awesome - that's great. Thanks for the link.

I based all of the work, so far, on [preact-markup](https://github.com/developit/preact-markup) - though that requires `preact` (and is incompatible with `react` due to the different `render` arguments being used).

If I have some time, I'll take a look at acorn.

RE: event-handling - I agree. At the moment, I'm considering leaving out support for it - because for my primary use-case, I'll be using `redux`-bound components, so I can add event handler bindings as part of the setup, rather than needing it in markup.

We should probably open a separate issue around support for events & syntax. Would you be interested in contributing?

**Comment by jonjaques** [comment]
Hi @TroyAlford, sorry for the long silence - Unfortunately I just don't have the time to devote to this right now, the stuff above was just me playing around one afternoon with dreams and aspirations for a personal project. I might pop back up at some point though 😄

**Comment by TroyAlford** [comment]
Totally understood!
