### ISSUE TITLE
Problem with code blocks

### ISSUE THREAD

**Issue by tudurom** [TroyAlford/react-jsx-parser#45]
Hi, I'm trying to pass something like 

```html
<pre><code class="markdown"># hello

a paragraph
</code></pre>
```

But instead of rendering nicely, the result is actually

```html
<pre><code class=""><undefined># hello		a paragraph</undefined></code></pre>
```

Is this a bug or am I doing something wrong?

**Comment by tudurom** [comment]
I created an empty issue by mistake btw, I edited it with the contents of the actual issue.

**Comment by tudurom** [comment]
Update: `<code>` doesn't need to be in a `<pre>` for this bug to happen

**Comment by TroyAlford** [comment]
Hmm... that's definitely a bug. It's almost certainly caused by [this line](https://github.com/TroyAlford/react-jsx-parser/blob/develop/source/components/JsxParser.js#L31). I'll try taking a look at it this afternoon, and see if simply removing the line fixes.

Thanks for the bug report!

**Comment by TroyAlford** [comment]
@tudurom - I can reproduce the part which trims out the line-breaks in the `code` block, but I cannot reproduce the stripping of `class` value, or the insertion of the `<undefined />` wrapper.

Can you please provide a snippet of your `<JsxParser />` declaration, with the props you're setting?

**Comment by TroyAlford** [comment]
I've just pushed a change that removes the stripping of `\r` and `\n` - which should repair this issue RE: `<code>` and `<pre>` blocks. It will go out with 1.2.6

**Comment by tudurom** [comment]
Now that the newlines aren't stripped anymore there are many empty `<undefined>` in the DOM.

![screenshot](https://ptpb.pw/pv6T.png)

**Comment by TroyAlford** [comment]
Hmm... I saw that pop up - but I was pretty sure that I had fixed it. I will try to do some poking at it this weekend to see if I can resolve.

**Comment by TroyAlford** [comment]
@tudurom - I can't reproduce this. As I requested previously, could you please show me how you're declaring your `<JsxParser />`, including the props, and give me an example of the JSX you are attempting to parse, as well?
