### ISSUE TITLE
Bindings are not handled when receiving new props

### ISSUE THREAD

**Issue by saendu** [TroyAlford/react-jsx-parser#49]
Hi Troy

I noticed that manipulating bindings via state do not reflect when the JsxParser component is rerendered. It looks like this is a by-design behaviour, since you do not handle new bindings as you handle blacklistedTags, blacklistedAttr and Jsx. Is there a possible reason for that? 

If so I would like to show you an akward behaviour that should be handled. Consider the following code:
```
class TitleComponent extends React.Component<any, any> {
  public render() {
    return(
      <h1>{this.props.text}</h1>
    );
  }
}

export class DynamicComponent extends React.Component<any, any> {
  constructor(props) {
      super(props);
      this.state = {text: "SOMETHING"};

      // change state 1
      setTimeout(() => {
        this.setState(previousState => {
          console.log("change state 1");
          return { text: "FIRST TITLE" };
        });
      }, 2000);

      // change state 2
      setTimeout(() => {
        this.setState(previousState => {
          console.log("change state 2");
          return { text: "SECOND TITLE" };
        });
      }, 4000);
  }

  public render() { 
    
    let textState = this.state.text; 
    
    // only showing 'FIRST TITLE' after (4 sec)
    return(
      <JsxParser
      bindings={{textState}}
      components={{ TitleComponent }}
      jsx={`<TitleComponent text={textState}/>`}
      />
    );
  }
}

```
This code is not working like expected, since the title component only gets updated after the second state change - however - showing 'FIRST TITLE' which was the props.binding object from the frist change. 

This could be fixed changing those two lines:

```
handleNewProps = (props) => {
     ...    
    this.bindings = (props.bindings || {})
    ...
  }
...
 parseExpression = (expression) => {
    switch (expression.type) {
      ...
      case 'Identifier':
        return this.bindings[expression.name] || undefined
      ...
    }
  }
```

Regards,
Sandro

**Comment by saendu** [comment]
#50 provided pull request

**Comment by TroyAlford** [comment]
Thanks for reporting this interesting problem - and also for the pull request! I'm checking it out now.

**Comment by TroyAlford** [comment]
I left a couple comments on the PR. This looks like an oversight which is, indeed, causing bug-like behavior. I look forward to having it resolved - and if you need me to help out with the PR, just let me know. :)

**Comment by saendu** [comment]
Thanks for v1.3.1 it resolved the binding state support. Also appreciate the MemberExpression support. That would have been another request of mine.
