### ISSUE TITLE
no support anonymous function

### ISSUE THREAD

**Issue by amily4555** [TroyAlford/react-jsx-parser#56]
```jsx
<MyFetch api='web.a.b'>
{(result) => ... }
</MyFetch>
```
anonymous function no running;

and 

i  tried to use binging = { callback: (result) => ... }
```jsx
<MyFetch api='web.a.b'>
{callback}
</MyFetch>
```
but MyFetch props.children = [symbol, function, symbol] 
I hope or the original MyFetch props.children = function

i must codeing
```jsx
<MyFetch api='web.a.b'>{callback}</MyFetch>
```

**Comment by TroyAlford** [comment]
Well - what you're doing, above, simply isn't a valid use-case. You can't just insert a function inside curly-brackets and expect it to be called - this doesn't work in React, either.

It's unclear to me what you're trying to accomplish from the above code. What is your expected result?
