### ISSUE TITLE
Since latest releases, `window` undefined while using the library with SSR 

### ISSUE THREAD

**Issue by patroza** [TroyAlford/react-jsx-parser#59]

**Comment by TroyAlford** [comment]
Hmmm - neato. I suspect it has something to do with upgrading webpack or babel. Can you create a minimal repro? I've never used the lib for SSR, myself, and I want to make sure I'm seeing what you're seeing.

**Comment by TroyAlford** [comment]
I'm going to close this issue now, due to lack of activity. I'm still happy to dig into it if you can provide a repro. Similarly - if you've solved it, I'd love to know what you needed to change in order to make it work!

**Comment by TroyAlford** [comment]
FYI - this issue should not exist in 1.3.3. There's some further activity on it in #64 - and I'm hoping to either create (or accept) a PR sometime soon. In the meantime, I suggest pinning to 1.3.3.

**Comment by TroyAlford** [comment]
This should now be fixed as of 1.3.6. Please let me know if you see it recur again!
