### ISSUE TITLE
Whitespace stripped between tags: problem for inline elements

### ISSUE THREAD

**Issue by zakness** [TroyAlford/react-jsx-parser#61]
Hi, I’m seeing an issue that causes inline elements to butt up against each other in specific situations.

The following examples demonstrate the input string (passed to the `jsx` prop) and the output HTML that is ultimately rendered. The example inputs are pure HTML as the issue is present even when no React components are injected.

In this example, the output is correct:

**Input**
```html
a b <strong>c</strong> <em>d</em>
```
**Output**
```html
<div class="jsx-parser">a b <strong>c</strong> <em>d</em></div>
```

However in this example, the output is incorrect (`c` and `d` have no space between them):

**Input**
```html
<p>a b</p>
<p><strong>c</strong> <em>d</em></p>
```
**Output**
```html
<div class="jsx-parser"><p>a b</p>
<p><strong>c</strong><em>d</em></p></div>
```

I’ve tested this with `renderInWrapper` both being `true` and `false` with the same results.

**Comment by TroyAlford** [comment]
Thanks for the report!

I suspect you have an out-of-date version of the lib. Could you please try updating to the latest and try again?

We definitely had this problem in the past - but it's been resolved for a while now, and we even have a test case that exercises this exact scenario. I also went ahead and recreated your test case, above, and can confirm that the current version runs as-intended, honoring the whitespace.

Let me know if that resolves, and if not we can work together further to figure out what's amiss.

**Comment by zakness** [comment]
Ah yep, I was on 1.2.1. 1.3.4 works like a charm.

What a rookie mistake! 😅

Thanks for the quick and thorough response!
