### ISSUE TITLE
Is it possible to pass a function to jsx template? 

### ISSUE THREAD

**Issue by erfansamieyan** [TroyAlford/react-jsx-parser#62]
Hi I've been using `react-jsx-parser` for days and it's been great till I tried to pass a custom function to the component that are passed as jsx template to the component. 
Look at the code below: 
`              <JsxParser
                components={{
                  MyComponent
                }}
                jsx={
                <MyComponent customName={'name'}
                    someObject={{name: 'foo',age: 25 }}
                    customFunction={(data)=>data.map(row=>row.name)}
                />}
              />`

`MyComponent` is rendering without problem and I can log and use `customName` and `someObject` easily inside the component but the custom function is always `undefined` in any condition. Even when I pass a simple function like `()=>{}` it just does not recognize it, but I really need to pass some custom functions in order to make it as flexible as I can. 
Any idea about that?

Thanks

**Comment by TroyAlford** [comment]
Hey there! Thanks for the praise, btw - always glad to meet folks who are using the lib. :)

The best way to accommodate what you're trying to do is with a custom binding:
```javascript
<JsxParser
  bindings={{
    dataBindingFn: (data) => data.map(row => row.name)
  }}
  components={{ MyComponent }}
  jsx={`
    <MyComponent 
      customName="name"
      someObject={{ name: 'foo', age: '25' }}
      customFunction={dataBindingFn}
    />
  `}
/>
```

The reason we don't allow custom functions the way you wrote it is that it opens the door for XSS attacks. Imagine a scenario in which you let users write JSX that you store in a database, and then parse on-the-fly client-side. A malicious user could suddenly generate javascript and have it executed on a remote browser by just setting a property value in the JSX. By forcing the `binding` props to be passed in, it precludes this from being so simple - and still allows you to create the binding as described above. :)

Please let me know if you have any trouble with it! Happy to help.

**Comment by erfansamieyan** [comment]
Thanks @TroyAlford for the great response and helping answer. But I still don't see that using binding is fully custom. As I understood the binding functions are still pre-written in the code and can't be injected by user. I tested the way you suggested and `(data) => data.map(row => row.name)` is passed fine and is able to be used by `MyComponent` but it is not still customized by user and we are not able to pre-write all possible cases and let the user choose. 
I see your point about security issues and it's completely valid, but imagine we have a private app that the administrator which is part of the developing team and wants to make some custom changes without changing the code. Do you mean that injecting code by user is not allowed at all?

**Comment by TroyAlford** [comment]
I suggest that you allow them to write the function as a string, in that
case, and then provide a component that accepts the string and runs `eval`
on it.

That would never be an appropriate thing to do it the code was editable by
end users, but if it's a trusted internal app, maybe it does make sense.

**Comment by erfansamieyan** [comment]
Yes, that's exactly what I finally did. 
User enters what (s)he wants as a string:

             <JsxParser
                components={{
                  MyComponent
                }}
                jsx={
                <MyComponent customName={'name'}
                    someObject={{name: 'foo',age: 25 }}
                    customFunction={'return data.map(row=>row.name)'}
                />}
              /> 

Inside the code it just needs to be converted into a function. 
`      const customBodyData = customData && new Function('data', customData);`
But finally as you mentioned it is important to no that using `eval` and `new Function` is not a secure way which opens the door to any injection by normal users and it should be only allowed for admins and special trusted users.
 
Thanks for your help

**Comment by TroyAlford** [comment]
Love it. :) Thanks for sharing your solution!
