### ISSUE TITLE
npmjs.com should link to this repository

### ISSUE THREAD

**Issue by sbusch** [TroyAlford/react-jsx-parser#69]
https://www.npmjs.com/package/react-jsx-parser contains no link to the URL of the GitHub repository.

Compare with https://www.npmjs.com/package/react ("repository" link)

When a new version for `react-jsx-parser` is published (`npm outdated`), when I google I usually only find the listing on npmjs.com, and this unfortunately contains no changelog.

**Comment by TroyAlford** [comment]
Good call. I never noticed that this info wasn't showing up properly. I'll work to fix that soon.

**Comment by TroyAlford** [comment]
My pleasure. :) Thanks for the kind words!

**Comment by TroyAlford** [comment]
This is resolved now, though the change required me to bump the version # to v1.5.1. :( Enjoy!
