### ISSUE TITLE
Warning: components must contain only subclasses of React.Component

### ISSUE THREAD

**Issue by jwickens** [TroyAlford/react-jsx-parser#7]
I get the following error when I render JsxParser in my app:
```
warning.js:36 Warning: Failed prop type: components must contain only Subclasses of React.Component or React.PureComponent.
    in t (at Message.js:48)
    in Message (at Message.js:20)
    in div (at decorators.js:26)
    in div (created by View)
    in View (at withChatContext.js:49)
    in ChatContext(function View(){_classCallCheck(this,View);return _possibleConstructorReturn(this,(View.__proto__||Object.getPrototypeOf(View)).apply(this,arguments));}) (at decorators.js:19)
```

Not sure what this is about. Do other people get this?

**Comment by TroyAlford** [comment]
https://github.com/TroyAlford/react-jsx-parser/blob/develop/src/components/JsxParser.js#L169 is what produces that error. It's attempting to ensure that you're passing in a valid component, which it knows about.

It's possible that you forgot to pass a prop of `components: [Message]`?

If not, let me know - happy to take a look.
