### ISSUE TITLE
use ...props in jsx attribute

### ISSUE THREAD

**Issue by mohsensaremi** [TroyAlford/react-jsx-parser#71]
how can i do somthing like this
`<JsxParser
    bindings={{
        className: classes.root,
        ...props
     }}
    components={{CurrencyLastUpdated}}
    jsx={'<div className={className} {...props}>test</div>'}
/>`

**Comment by TroyAlford** [comment]
That snippet isn't really enough for me to understand what you're attempting to accomplish. Could you please explain further?
