### ISSUE TITLE
Supporting unary negation

### ISSUE THREAD

**Issue by hokevins** [TroyAlford/react-jsx-parser#72]
Hi, does `react-jsx-parser` currently support [unary operator negation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Unary_negation_(-)) i.e. something like -75 as the value for a prop in its output components?

I am currently using `react-jsx-parser` to take in a string of JSX to output a series of React components.  I'm passing this string of JSX as `content` in `jsx={content}` for JsxParser.

One of my components takes a prop called `min` which must be a number (can be a negative number).  So when I pass in `min={75}` into this component, react-jsx-parser correctly passes the prop through to the component with the value 75.  But when I pass in `min={-75}`, react-jsx-parser produces `undefined` as the value for the `min` prop.

The culprit, I believe, may be the switch statement on Line 46 of [`react-jsx-parser/source/components/JsxParser.js`](https://github.com/TroyAlford/react-jsx-parser/blob/develop/source/components/JsxParser.js) where the default returns `undefined`.

Please kindly advise and/or suggest a workaround, or am I possibly using `react-jsx-parser` wrong?
Thank you.

**Comment by TroyAlford** [comment]
@hokevins I think you're exactly right. This is another operator that needs support. I can't take a look at it right at the moment - but it should be pretty straightforward to implement. If you'd like to submit a PR, I'd be happy to review it and get things moving. Otherwise, I'm afraid we'll be a bit subject to my schedule, before I can get around to it. :(

**Comment by hokevins** [comment]
@TroyAlford Thanks for your response, I'd be happy to give it a shot and submit a PR for this feature request.  I don't see a CONTRIBUTION.md file, so feel free to let me know if there are any contribution guidelines you'd like for me to adhere to in my PR.  Thank you.

**Comment by TroyAlford** [comment]
Ooh - good point. I should add that. 3 things, basically:
 - ESLint needs to pass
 - All unit tests need to pass
 - Please add unit test(s) for your changes, following the existing unit tests as a guide

**Comment by hokevins** [comment]
Hi, [PR#74 as above](https://github.com/TroyAlford/react-jsx-parser/pull/74), is ready for your review for `react-jsx-parser`.  ESLint, unit tests all pass, added unit tests too for my feature request.

I did not commit my local copy of `react-jsx-parser.min.js` though as I wasn't sure about your build/deploy/sem-ver workflow.  Please kindly advise.

**Comment by TroyAlford** [comment]
Thanks, @hokevins! This looks great. :) I left a couple comments - and I'll work on getting the CI part to pass once we get this merged in.

**Comment by hokevins** [comment]
Hi @TroyAlford , thanks for the feedback, I've updated the PR to address your comments.  =)

**Comment by TroyAlford** [comment]
@hokevins thanks a bunch for the PR! I've just merged and pushed this as `1.13.0` :)

**Comment by hokevins** [comment]
Thank you as well for providing such a useful library!  =)
