### ISSUE TITLE
Input lost focus when parent component rerender

### ISSUE THREAD

**Issue by qq181621732** [TroyAlford/react-jsx-parser#73]
**Input will lost focus when we key in.**  

```
export default class ParentComponet extends React.PureComponent {
  constructor(props) {
    super(props)
    this.handleChange = this.handleChange.bind(this)
    this.state = {value: '1'}
  }
  handleChange(event) {
    this.setState({
      value: event.target.value
    })
  }
  render() {
    return (
      <JsxParser
        bindings={{
          value: this.state.value,
          handleChange: this.handleChange,
        }}
        components={{}}
        jsx={"<input type='text' value={value} onChange={handleChange} />"}/>
    )
  }
}
```

how can i avoid this?

**Comment by TroyAlford** [comment]
```javascript
class App extends Component {
  state = { value: '1' }

  handleChange = (event) => {
    console.log(event.target.value)
    this.setState({
      value: event.target.value
    })
  }

  render() {
    return (
      <JsxParser
        bindings={{
          value: this.state.value,
          handleChange: this.handleChange,
        }}
        blacklistedAttrs={[]}
        components={{}}
        jsx={"<input key='input' type='text' value={value} onChange={handleChange} />"}/>
    )
  }
}
```

Two problems I see. First, you need the `blacklistedAttrs={[]}`, because otherwise the `onChange` handler will never be bound, to begin with. The default is to blacklist any attribute which starts with `on`.

The second thing is to simply give the `input` box a `key` attribute. In the example above, I just used `key='input'` - it doesn't really matter what it is, as long as its consistent. This lets React understand that the element being rendered matches the previous rendition of itself. Without the key, you get a _new_ `input` on each render - and the render is caused by your `setState({})`.

**Comment by qq181621732** [comment]
> ```js
> class App extends Component {
>   state = { value: '1' }
> 
>   handleChange = (event) => {
>     console.log(event.target.value)
>     this.setState({
>       value: event.target.value
>     })
>   }
> 
>   render() {
>     return (
>       <JsxParser
>         bindings={{
>           value: this.state.value,
>           handleChange: this.handleChange,
>         }}
>         blacklistedAttrs={[]}
>         components={{}}
>         jsx={"<input key='input' type='text' value={value} onChange={handleChange} />"}/>
>     )
>   }
> }
> ```
> 
> Two problems I see. First, you need the `blacklistedAttrs={[]}`, because otherwise the `onChange` handler will never be bound, to begin with. The default is to blacklist any attribute which starts with `on`.
> 
> The second thing is to simply give the `input` box a `key` attribute. In the example above, I just used `key='input'` - it doesn't really matter what it is, as long as its consistent. This lets React understand that the element being rendered matches the previous rendition of itself. Without the key, you get a _new_ `input` on each render - and the render is caused by your `setState({})`.

Thanks for your help!
If the input box is in a div, we should also put key attribute in the div.
`  jsx={"<div  key='input'><input key='input' type='text' value={value} onChange={handleChange} /></div>"}/>`
