### ISSUE TITLE
Is there a version of package with acorn minified for production?  Package large with unminified.

### ISSUE THREAD

**Issue by juneshaw** [TroyAlford/react-jsx-parser#76]

**Comment by TroyAlford** [comment]
Hi @juneshaw - I haven't done anything special to minify `acorn` if that's what you mean. The reference to it is: https://github.com/TroyAlford/react-jsx-parser/blob/develop/source/components/JsxParser.js#L1, which depends on `acorn-jsx` - which, in turn, pulls in `acorn` itself. That's where all the size comes from.

At the moment, I'm unaware of any good mechanism for further smashing the files, here - beyond perhaps webpacking my `node_modules` - but if you have some insights as to ways we can optimize, I'd love a PR!
