### ISSUE TITLE
Allow inline function declarations

### ISSUE THREAD

**Issue by Abdubek** [TroyAlford/react-jsx-parser#94]
The documentation says:
![image](https://user-images.githubusercontent.com/16240224/59485109-47a8e380-8e96-11e9-9508-0984d4e2fe31.png)

my task doesn't need security. Each user deploys the application on his computer.

Can I allow the use of inline functions?

**Comment by Abdubek** [comment]
Can you tell me how to enable functions in jsx. I still want a cycle to output dynamic data

**Comment by TroyAlford** [comment]
I apologize, @Abdubek - I will not enable declaring functions in JSX strings for this lib. There are too many levels of complexity, on top of the security implications.

**Comment by mjsgreen01** [comment]
bummer.

**Comment by KhalfaniW** [comment]
If you don't need security, you can just parse the string using @babel/standalone and eval the string.

**Comment by stoefln** [comment]
I also don't need the security but I don't get how babel can be used in the same way as react-jsx-parser.
@KhalfaniW could you give me a hint? It seems @babel/parser is transforming JSX to AST, but how do I actually "render" this AST then as html to my page? And how do I pass bindings?

@mjsgreen01 did you ever find a solution?

**Comment by KhalfaniW** [comment]
@stoefln  [@babel/standalone](https://babeljs.io/docs/en/babel-standalone)  is a separate package that can transform JSX into a js string on it's own 

If you want to run react from a string you can write a react component and the code to render it in JSX. Then convert all that into js.

``` 
  const sampleReactCode = `
const SampleComponent = ()=>{
   const [count,setCount] = React.useState(0);
   return <button onClick={
   ()=>{setCount(currentCount=>currentCount+1)}
   }> Count {count}</button>
   
}

  ReactDOM.createRoot(document.getElementById('root-react-element')).render(
 <SampleComponent/>
)
`
```


Babel standalone offers a function to transform this string into regular js.

`const codeToEval = Babel.transform( sampleReactCode,{ presets: ["react", ["es2015", { modules: true}]]}).code`

When you eval this code it will inject react code into the element the same way you inject react into the `index.html` in full react projects.

Here is a code pen example
https://codepen.io/khalfaniw/pen/MWBpLMm

**Comment by stoefln** [comment]
Thanks so much @KhalfaniW, that's a huge help!!
BTW: The reason I don't need the security aspect is that I am using the react parser inside of an electron application, so it runs locally.

**Comment by stoefln** [comment]
Maybe one more question:
I managed to set up @babel/standalone, but I am using a view inside my react app as the root for "createRoot" (actually I am using ReactDOM.render(<Comp />, rootElement)).

However, I am now getting this warning: 

> Warning: render(...): Replacing React-rendered children with a new root component. If you intended to update the children of this node, you should instead have the existing children update their state and render the new components instead of calling ReactDOM.render.

That's kind of clear. The effect is, that if I change to another page and get back to this page (main React is replacing the child react container), my changes are gone.

So I guess my question is: How can I render the child react container, inside of the main react container? Or to put it differently: Where should I call `eval(codeToEval)`, so it also get's rebuilt when the main react container rerenders?

**Comment by TroyAlford-RL** [comment]
Though I do appreciate you guys working this out - please do not debug a different application in the issue thread for this repo.

**Comment by stoefln** [comment]
I get that this doesn't belong here theoretically speaking, but in practice, it might be exactly the place where people will be looking for it. There is a reason why I ended up here.
