### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by giangldo** [TroyAlford/react-jsx-parser#96]
Hi,
I found an error in the latest version "react-jsx-parser": "^1.18.0".

But no error "react-jsx-parser": "^1.16.1".

My code example.

`
// Loadable == component require export as default
const TemplateHtml = Loadable({
    loader: () =>
      import("../../modules" + component) as Promise<IFunctionComponent>,
    render(loaded: IFunctionComponent) {
      const Component: FunctionComponent = loaded.default;
      const dynamicHtml: string = "<div>hello <Component {...props} /></div>";

      return (
        <JsxParser
          bindings={{ props }}
          components={{ Component }}
          jsx={dynamicHtml}
        />
      );
    },
    loading: () => <div>loading</div>,
  });
`

Thanks for your helps,
GD

**Comment by petertenhoor** [comment]
Can confirm that updating react-jsx-parser to the latest version started throwing these warnings:

```Warning: Each child in a list should have a unique "key" prop.```

**Comment by TroyAlford** [comment]
This should now be resolved in `v1.19.1` :) Please let me know if you see further problems!

**Comment by nayaabkhan** [comment]
Looks like this warning is back. I'm using the latest version. @giangldo can you please reopen?
