### ISSUE TITLE
Conditional expressions are not working.

### ISSUE THREAD

**Issue by SuriyaJin** [TroyAlford/react-jsx-parser#97]
Example:
bindings={{id: 157}}

`<div>{id === 157 ? "true":"false"}</div>`

this always displays true.
acts in same behavior for changing attributes of html elements by using conditions.
Example:
`<div className={id === 157 ? "red-class":"blue-class"}>{id === 157 ? "true":"false"}</div>`

**Comment by TroyAlford** [comment]
@SuriyaJin - in your example, you have effectively hard-coded `id` to always equal `157` - so it makes sense that it will always display `true`, based on your ternary expression.

I just wrote a unit test for this, and it seems to work as-expected. Perhaps your code is not successfully changing the `bindings` value of `id`?
